// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpoOvU4FbzpvC1I9pyeCUXY4MF3b1HC6o',
    appId: '1:981788314186:web:bd509f02dff8927112f4b3',
    messagingSenderId: '981788314186',
    projectId: 'caloriesgram-459d9',
    authDomain: 'caloriesgram-459d9.firebaseapp.com',
    storageBucket: 'caloriesgram-459d9.appspot.com',
    measurementId: 'G-LFYKQ2EK26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMHsEgYwHII2LnueedUTgLEktmW34q5l0',
    appId: '1:981788314186:android:70881987bc21d2c912f4b3',
    messagingSenderId: '981788314186',
    projectId: 'caloriesgram-459d9',
    storageBucket: 'caloriesgram-459d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIAwxzP0QCoHpnJaf-HqDLeRGYYkQtZWE',
    appId: '1:981788314186:ios:ab65504fa219e57d12f4b3',
    messagingSenderId: '981788314186',
    projectId: 'caloriesgram-459d9',
    storageBucket: 'caloriesgram-459d9.appspot.com',
    iosClientId: '981788314186-i2biqfogmrmjga6d59102nfiefi6bq7l.apps.googleusercontent.com',
    iosBundleId: 'com.caloriesgram.caloriesgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIAwxzP0QCoHpnJaf-HqDLeRGYYkQtZWE',
    appId: '1:981788314186:ios:ab65504fa219e57d12f4b3',
    messagingSenderId: '981788314186',
    projectId: 'caloriesgram-459d9',
    storageBucket: 'caloriesgram-459d9.appspot.com',
    iosClientId: '981788314186-i2biqfogmrmjga6d59102nfiefi6bq7l.apps.googleusercontent.com',
    iosBundleId: 'com.caloriesgram.caloriesgram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpoOvU4FbzpvC1I9pyeCUXY4MF3b1HC6o',
    appId: '1:981788314186:web:2138a86e26628d2712f4b3',
    messagingSenderId: '981788314186',
    projectId: 'caloriesgram-459d9',
    authDomain: 'caloriesgram-459d9.firebaseapp.com',
    storageBucket: 'caloriesgram-459d9.appspot.com',
    measurementId: 'G-0T77BRK3BX',
  );

}